name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build SUT
        run: java -jar ./artifacts/app-card-delivery.jar > app_log.txt 2>&1 &

      - name: Check if app is running
        run: |
          ps aux | grep app-card-delivery.jar

      - name: Show app logs if failed
        run: cat app_log.txt

      - name: Wait for the application to be up
        run: |
          attempts=0
          max_attempts=20  # увеличено количество попыток
          until curl --silent --fail http://localhost:9999 || [ $attempts -ge $max_attempts ]; do
            echo "Waiting for application to start... Attempt $((attempts+1))"
            attempts=$((attempts+1))
            # Печатаем логи приложения, чтобы увидеть, что происходит
            cat app_log.txt
            sleep 5
          done
          if [ $attempts -ge $max_attempts ]; then
            echo "Application did not start within the expected time."
            exit 1
          fi

      - name: Run tests
        run: ./gradlew test --stacktrace --info -Dselenide.headless=true
